# Generated by Django 5.0.2 on 2024-03-20 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posting", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserAvatar",
            new_name="ProfilePicture",
        ),
    ]
