# Generated by Django 5.0.2 on 2024-03-01 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posting", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "Profile"},
        ),
    ]
