# Generated by Django 5.0.2 on 2024-03-21 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posting", "0002_rename_useravatar_profilepicture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilepicture",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="picture",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
