# Generated by Django 5.0.2 on 2024-03-03 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posting", "0002_alter_user_birthday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="sex",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("U", "Undefined")],
                default="U",
                max_length=1,
                verbose_name="sexo",
            ),
        ),
    ]
