# Generated by Django 5.0.2 on 2024-03-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posting", "0002_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.FileField(blank=True, upload_to="avatars"),
        ),
    ]
