# Generated by Django 5.0.2 on 2024-03-11 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posting", "0003_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image_content",
            field=models.ImageField(blank=True, null=True, upload_to="img"),
        ),
    ]
