# Generated by Django 5.0.2 on 2024-03-21 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posting", "0003_alter_profilepicture_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilepicture",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_picture",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
