# Generated by Django 5.0.2 on 2024-04-08 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posting", "0012_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="liked_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
